name: Run Selenium Tests and Generate Allure Report

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
      - name: Verify test suite XML file
        run: ls Opollo/src/test/testCreatePOMS.xml
      - name: Check Java version
        run: java -version
      - name: Check Maven version
        run: mvn -version
      - name: Run tests
        working-directory: Opollo
        run: mvn clean test -Dsurefire.suiteXmlFiles=src/test/testCreatePOMS.xml
      - name: Check compiled test classes
        working-directory: Opollo
        run: ls target/test-classes || echo "No compiled test classes found"