name: Run Selenium Tests and Generate Allure Report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '18'

      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y chromium-chromedriver

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          maven-version: 3.10.1

      - name: Install Allure
        run: |
          sudo apt-add-repository ppa:qameta/allure
          sudo apt-get update
          sudo apt-get install -y allure

      - name: Run tests
        working-directory: Opollo
        run: |
          mkdir -p allure-results
          mvn clean test -Dsurefire.suiteXmlFiles=src/test/resources/testCreatePOMS.xml -DtestingUrl=https://dev-admin.onpoint.vn
        env:
          ALLURE_RESULTS_DIR: allure-results

      - name: Generate Allure report
        working-directory: Opollo
        run: |
          mkdir -p ../allure-report
          allure generate allure-results --clean -o ../allure-report

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report  # Deploy directly to repo root
          publish_branch: gh-pages