name: Run Selenium Tests and Generate Allure Report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '18'

      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y chromium-chromedriver

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          maven-version: 3.10.1

      - name: Run tests
        run: |
          mkdir -p Opollo/allure-results
          mvn clean test -Dsurefire.suiteXmlFiles=src/test/testCreatePOMS.xml -DtestingUrl=https://dev-admin.onpoint.vn
        env:
          ALLURE_RESULTS_DIR: Opollo/allure-results

      - name: Generate Allure report
        run: |
          mkdir -p Opollo/allure-report
          allure generate Opollo/allure-results --clean -o Opollo/allure-report

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Opollo/allure-report
          publish_branch: gh-pages

      - name: Read index.html from Allure Report
        run: cat Opollo/allure-report/index.html